import type { CatalogStore, PlantListItem, PlantDetail } from "./types";

// Mock plant data
const mockPlants: PlantDetail[] = [
  {
    id: "1",
    name: "Snake Plant",
    scientificName: "Sansevieria trifasciata",
    category: "Indoor plant",
    light: "Bright indirect",
    airPurifier: "Yes",
    horticulturistNotes: "Extremely low-maintenance plant perfect for beginners. Tolerates neglect and low light conditions. Excellent air purifier. Water sparingly - only when soil is completely dry. Can go weeks without watering.",
    wateringRequirement: "Low",
    soilMix: "Well-draining cactus mix or regular potting soil with perlite",
    fertilizationRequirement: "Fertilize monthly during growing season (spring-summer) with diluted houseplant fertilizer",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
  {
    id: "2",
    name: "Money Plant",
    scientificName: "Epipremnum aureum",
    category: "Creepers",
    light: "Bright indirect",
    airPurifier: "Yes",
    horticulturistNotes: "Popular trailing plant that grows quickly in Bangalore's climate. Excellent for hanging baskets or training up supports. Very forgiving and propagates easily from cuttings.",
    wateringRequirement: "Medium",
    soilMix: "Standard potting mix with good drainage",
    fertilizationRequirement: "Feed every 4-6 weeks during growing season",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
  {
    id: "3",
    name: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    category: "Flowering",
    light: "Bright indirect to partial shade",
    airPurifier: "Yes",
    horticulturistNotes: "Beautiful flowering plant that thrives in Bangalore's humidity. White flowers bloom throughout the year. Excellent indicator plant - droops when it needs water.",
    wateringRequirement: "Medium",
    soilMix: "Rich, well-draining potting mix with organic matter",
    fertilizationRequirement: "Fertilize monthly with balanced liquid fertilizer",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
  {
    id: "4",
    name: "Aloe Vera",
    scientificName: "Aloe barbadensis miller",
    category: "Indoor plant",
    light: "Full sunlight (6-8 hours)",
    airPurifier: "No",
    horticulturistNotes: "Hardy succulent perfect for Bangalore balconies with direct sunlight. Medicinal properties - gel can be used for skin burns and cuts. Very drought-tolerant.",
    wateringRequirement: "Low",
    soilMix: "Cactus or succulent mix with sand and perlite",
    fertilizationRequirement: "Fertilize 2-3 times per year during growing season with succulent fertilizer",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
  {
    id: "5",
    name: "Tulsi (Holy Basil)",
    scientificName: "Ocimum tenuiflorum",
    category: "Aromatic",
    light: "Full sunlight (6-8 hours)",
    airPurifier: "Yes",
    horticulturistNotes: "Sacred herb in Indian culture, thrives in Bangalore's climate. Aromatic leaves used in cooking and Ayurvedic medicine. Regular pruning encourages bushier growth.",
    wateringRequirement: "Medium",
    soilMix: "Well-draining soil with compost",
    fertilizationRequirement: "Feed with organic compost or liquid fertilizer every 2-3 weeks during growing season",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
  {
    id: "6",
    name: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    category: "Indoor plant",
    light: "Bright indirect",
    airPurifier: "Yes",
    horticulturistNotes: "One of the easiest plants to grow. Produces baby spiderettes that can be propagated. Great air purifier. Handles Bangalore's humidity well.",
    wateringRequirement: "Medium",
    soilMix: "Well-draining potting mix",
    fertilizationRequirement: "Fertilize monthly during spring and summer",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
  {
    id: "7",
    name: "Jade Plant",
    scientificName: "Crassula ovata",
    category: "Indoor plant",
    light: "Full sunlight (6-8 hours)",
    airPurifier: "No",
    horticulturistNotes: "Slow-growing succulent that can live for decades. Symbolizes good luck and prosperity. Thick, glossy leaves store water. Perfect for sunny balconies.",
    wateringRequirement: "Low",
    soilMix: "Well-draining succulent mix",
    fertilizationRequirement: "Feed sparingly - once every 2-3 months during growing season",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
  {
    id: "8",
    name: "Croton",
    scientificName: "Codiaeum variegatum",
    category: "Indoor plant",
    light: "Full sunlight (6-8 hours)",
    airPurifier: "No",
    horticulturistNotes: "Colorful variegated leaves in shades of red, orange, yellow, and green. Requires bright light to maintain vibrant colors. Needs consistent humidity.",
    wateringRequirement: "Medium",
    soilMix: "Rich, well-draining potting soil",
    fertilizationRequirement: "Fertilize every 2-3 weeks during growing season with balanced fertilizer",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
  {
    id: "9",
    name: "Lucky Bamboo",
    scientificName: "Dracaena sanderiana",
    category: "Indoor plant",
    light: "Medium indirect",
    airPurifier: "Yes",
    horticulturistNotes: "Can grow in water or soil. Popular Feng Shui plant. Easy to maintain. Change water weekly if growing hydroponically. Grows well in Bangalore's climate.",
    wateringRequirement: "High",
    soilMix: "Rich, well-draining soil or water with pebbles",
    fertilizationRequirement: "If in water, add liquid fertilizer monthly. If in soil, fertilize every 6-8 weeks",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
  {
    id: "10",
    name: "Pothos",
    scientificName: "Epipremnum aureum",
    category: "Creepers",
    light: "Bright indirect to partial shade",
    airPurifier: "Yes",
    horticulturistNotes: "Incredibly hardy trailing plant. Perfect for beginners. Tolerates low light and irregular watering. Great for hanging baskets. Fast-growing in Bangalore.",
    wateringRequirement: "Low",
    soilMix: "Standard potting mix",
    fertilizationRequirement: "Fertilize monthly during growing season",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
  {
    id: "11",
    name: "Areca Palm",
    scientificName: "Dypsis lutescens",
    category: "Indoor plant",
    light: "Full- partial sunlight (4-6 hours)",
    airPurifier: "Yes",
    horticulturistNotes: "Beautiful feathery palm perfect for Bangalore balconies. Adds tropical feel. Requires regular misting. Great air purifier. Can grow quite tall with proper care.",
    wateringRequirement: "Medium",
    soilMix: "Rich, well-draining potting mix with sand",
    fertilizationRequirement: "Feed with palm fertilizer every 2-3 months during growing season",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
  {
    id: "12",
    name: "Marigold",
    scientificName: "Tagetes erecta",
    category: "Flowering",
    light: "Full sunlight (6-8 hours)",
    airPurifier: "No",
    horticulturistNotes: "Bright, cheerful flowers perfect for Bangalore balconies. Blooms throughout the year. Natural pest deterrent. Low maintenance and great for beginners.",
    wateringRequirement: "Medium",
    soilMix: "Well-draining garden soil with compost",
    fertilizationRequirement: "Feed with balanced fertilizer every 2-3 weeks during blooming period",
    thumbnailUrl: "/images/plant-placeholder.svg",
    imageUrl: "/images/plant-placeholder.svg",
  },
];

// Mock Catalog Store Implementation
class MockCatalogStore implements CatalogStore {
  async listPlants(): Promise<PlantListItem[]> {
    // Return lightweight list items
    return mockPlants.map((plant) => ({
      id: plant.id,
      name: plant.name,
      category: plant.category,
      light: plant.light,
      thumbnailUrl: plant.thumbnailUrl,
      airPurifier: plant.airPurifier,
      toxicity: plant.toxicity,
    }));
  }

  async getPlantById(id: string): Promise<PlantDetail | null> {
    const plant = mockPlants.find((p) => p.id === id);
    return plant || null;
  }
}

export const mockCatalogStore = new MockCatalogStore();
